# Model Configuration
model:
  base_model_id: "unsloth/llama-3.2-3b-instruct-bnb-4bit"
  #model_id: "meta-llama/Llama-3.2-3B-Instruct"
  model_id: "Jithendra-k/Emotion_Aware_Chat_LLM"
  #model_id: "Jithendra-k/EGRET_LLM"
  use_auth_token: true
  device: "cuda"  # Change to "cpu" if CUDA not available
  max_length: 512
  temperature: 0.7
  top_p: 0.9
  num_responses: 3

# Graph Configuration
graph:
  max_history: 10
  emotion_threshold: 0.7
  base_patterns_path: "data/emotion_patterns/base_patterns.json"
  save_path: "data/emotion_patterns/current_graph.json"
  update_frequency: 5  # Save graph every N messages

# Preference Configuration
preference:
  history_path: "data/preference_history/preferences.json"
  score_decay: 0.9
  min_score: 0.1

# UI Configuration
ui:
  debug_mode: false
  max_chat_history: 50
  show_emotion_graph: true
  response_options: 3

# System Configuration
system:
  seed: 42
  debug: false
  log_level: "INFO"
  save_conversations: true


